name: Contracts

on:
  pull_request:
  push:
    branches:
      - main

env:
  TURBO_TELEMETRY_DISABLED: 1
  COMPILER_VERSION: "0.26.0"

jobs:
  pipeline:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2 # Recommended by turbo team
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Check compiler version
        run: |
            export PATH="$HOME/.compact/bin:$PATH"
            COMPILER_OUTPUT=$(compact compile --version)
            COMPUTED_COMPILER_VERSION=$(echo "$COMPILER_OUTPUT" | grep -oP '\b0\.[0-9]+\.[0-9]+\b' | head -n 1)
            if [ "$COMPUTED_COMPILER_VERSION" != "$COMPILER_VERSION" ]; then
              errMsg="‚ùå Compiler version mismatch!%0AExpected: $COMPILER_VERSION%0AGot: $COMPUTED_COMPILER_VERSION"
              echo "::error::$errMsg"
              exit 1
            fi
            echo "‚úÖ Compiler version matches: $COMPUTED_COMPILER_VERSION"

            echo "üìã Language version:"
            compact compile --language-version

      - name: Run tests
        run: pnpm test:contracts

      - name: Check types
        run: pnpm exec turbo run types --filter './contracts/*'
